// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Button--isDisabled': string;
  'Button--isSecondary': string;
  'Button__icon': string;
  'Button__icon--left': string;
  'Button__icon--right': string;
}
export const cssExports: CssExports;
export default cssExports;
