// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Overlay': string;
  'Overlay--isAbsolute': string;
  'Overlay--isTransparent': string;
}
export const cssExports: CssExports;
export default cssExports;
